name: AWS-ECR
on: 
  pull_request:
    types: [closed]
  push:
    branches:
      - main
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true || contains(github.event.head_commit.message, '@[build]')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: SpicyPizza/create-envfile@master
      with:
        envkey_ATLAS_URI: ${{ secrets.DB_CONNECTION_STRING }}
        envkey_NOT_FOUND_URL: ${{ secrets.NOT_FOUND_URL }}
    - uses: kciter/aws-ecr-action@v3
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        dockerfile: Dockerfile-api
        repo: kapsule/kapsule-api
        region: eu-central-1
        tags: latest,${{ github.sha }}
        create_repo: true
        set_repo_policy: true
        repo_policy_file: repo-policy.json
    - uses: kciter/aws-ecr-action@v3
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        dockerfile: Dockerfile-redirect
        repo: kapsule/kapsule-redirect
        region: eu-central-1
        tags: latest,${{ github.sha }}
        create_repo: true
        set_repo_policy: true
        repo_policy_file: repo-policy.json

